services:
  - type: web
    name: cashbook-backend
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_FILE
        value: /data/cashlink.db
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 