services:
  - type: web
    name: cashbook-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node src/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000 