services:
  - type: web
    name: cashbook-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_FILE
        value: /data/cashlink.db
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: CHROME_PATH
        value: "/usr/bin/google-chrome-stable"
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
    healthCheckPath: /
    autoDeploy: true 